---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Stale

on:
  schedule:
    - cron: "0 8 * * *" # Every day at 08:00
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read
  packages: read
  statuses: read

jobs:
  stale:
    name: 🧹 Clean up stale issues and PRs
    runs-on: ubuntu-latest

    permissions:
      contents: write # only for delete-branch option
      issues: write
      pull-requests: write
    steps:
      - uses: ivuorinen/actions/stale@1da3a0e79fcd7da6bed9ee1979f1449ba11f58f9 # v2026.03.14
