---
name: Update Browserslist database

on:
  schedule:
    # At 02:00 on day-of-month 1 and 15.
    - cron: '0 2 1,15 * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-browserslist-database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4.2.0
        with:
          always-auth: true
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'
          scope: '@ivuorinen'

      - name: Configure git
        run: |
          git config user.name "fiximus"
          git config user.email "189535814+fiximus@users.noreply.github.com"

      - name: Update Browserslist database and create PR if applies
        uses: c2corg/browserslist-update-action@v2.5.0
        with:
          directory: ./packages/browserslist-config/
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ vars.BROWSERSLIST_UPDATE_BRANCH || 'browserslist-update' }}
          base_branch: ${{ vars.DEFAULT_BRANCH || 'main' }}
          commit_message: 'chore(deps): update browserslist database'
          title: 'chore(deps): update browserslist database'
          body: Auto-generated by [browserslist-update-action](https://github.com/c2corg/browserslist-update-action/)
          labels: 'maintenance'
          reviewers: 'ivuorinen'
